laba1
SadigMamedov/labaOOP1 pull request #1
Opened 2022-06-12 14:49 UTC by SadigMamedov

Добрый День!
это первая лаба по ооп, посмотрите пожалуйста! @Sych474

2022-06-13 21:17 UTC, Sych474 requested changes

2022-06-13 21:17 UTC, Sych474 commented on laba1_OOP/laba1_OOP/testing.cpp
> +    std::cout << "Test for changing a list item by index PASSED" << "\n\n";
В случае ошибки будет выведено и Failed и Passed, в остальных тестах также стоит проверить этот случай.

2022-06-13 21:17 UTC, Sych474 commented on laba1_OOP/laba1_OOP/testing.cpp
> +        std::cout << msg << "\n\n";
Тут у вас не понятно - это ошибочный тест, или так и должно быть по выводу, стоит уточнить.

2022-06-13 21:17 UTC, Sych474 commented on laba1_OOP/laba1_OOP/testing.cpp
> +        std::cout << msg << "\n\n";
И тут уточнить, и в других подобных местах.

2022-06-13 21:17 UTC, Sych474 commented on laba1_OOP/laba1_OOP/testing.cpp
> +    if (lst.get_index(elem2) != -1)
Разделить на два теста т.к. проверяете 2 случая.

2022-06-13 21:17 UTC, Sych474 commented on laba1_OOP/laba1_OOP/iterator.h
> +        throw "The list is empty";
`The list is null`, потому что список не пустой. а не существует.

2022-06-13 21:17 UTC, Sych474 commented on laba1_OOP/laba1_OOP/list.h
> +    T* mas = new T[this->quantity];
Имеет смысл выделять память после проверки на null

2022-06-14 22:23 UTC, SadigMamedov commented on laba1_OOP/laba1_OOP/list.h
> +    T* mas = new T[this->quantity];
нет, не имеет смысла. потому что после проверки на null у нас идёт ошибка и программа аварийно завершается

2024-12-24 10:56 UTC, closed without merging